### ISSUE TITLE
Not support Utf8

### ISSUE THREAD

**Issue by Saeb-K** [FmWebStudio/IPS-Telegram-Share-Link#1]
This plugin when the links are in the form of non-English Shares able to create links is not correct and not consistent with utf8.

**Comment by Recouse** [comment]
Can I get link to your site?

**Comment by Saeb-K** [comment]
yes if The title this problem will happen if non-Latin
http://goo.gl/qIBPyr

**Comment by Recouse** [comment]
I've never had to deal with such and I think that is the telegram's bug.

**Comment by Recouse** [comment]
I've never had to deal with such.
But such as twitter are no problems.

**Comment by Saeb-K** [comment]
But only posts that they are non-English title is displayed for incorrect telegrams

**Comment by Recouse** [comment]
Russian posts display correct.  I think that is the telegram's bug.

**Comment by Saeb-K** [comment]
Yes, and for English to Arabic and Persian also not a problem but the problem is that the test
